import type { Metadata } from 'next'
import './globals.css'
import { Figtree } from '@next/font/google'

const figtree = Figtree({
  weight: ['400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
  variable: '--font-figtree',
})

export const metadata: Metadata = {
  title: 'Educanutri',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='pt-br' className='flex flex-col items-center justify-between h-screen'>
      <body className={`${figtree.className} antialiased h-screen px-6 py-24`}>
        {children}
      </body>
    </html>
  )
}
